---
image: docker:///concourse/testflight

paths:
  testflight: gopath/src/github.com/concourse/testflight
  atc: gopath/src/github.com/concourse/atc
  turbine: gopath/src/github.com/concourse/turbine
  fly: gopath/src/github.com/concourse/fly
  warden-linux: gopath/src/github.com/cloudfoundry-incubator/warden-linux

run:
  path: gopath/src/github.com/concourse/testflight/scripts/test
