---
image: concourse/testflight

env:
  - GOROOT: /usr/local/go
  - PATH: $GOROOT/bin:$PATH
  - BASE_GOPATH: /tmp/build/src/gopath
  - GOPATH: ${BASE_GOPATH}:/tmp/build/src/testflight/Godeps/_workspace
  - PATH: ${BASE_GOPATH}/bin:$PATH
  - PATH: /tmp/build/src/testflight/Godeps/_workspace/bin:$PATH
  - DOCKER_REGISTRY_CONFIG: /docker-registry/config/config_sample.yml
  - EXTERNAL_ADDRESS: $(ip route get 8.8.8.8 | sed 's/.*src\s\(.*\)\s/\1/;tx;d;:x')

script: |
  set -e -x

  function copy_to_gopath {
    mkdir -p ${BASE_GOPATH}/src/${1}
    rsync --del --exclude '.*' -a $(basename $1)/ ${BASE_GOPATH}/src/${1}/
  }

  copy_to_gopath github.com/concourse/testflight
  copy_to_gopath github.com/winston-ci/winston
  copy_to_gopath github.com/winston-ci/prole
  copy_to_gopath github.com/winston-ci/redgreen
  copy_to_gopath github.com/winston-ci/smith
  copy_to_gopath github.com/cloudfoundry-incubator/warden-linux

  pushd warden-linux/
    make # compile wshd/etc.
    export WARDEN_BINPATH=$PWD/linux_backend/bin
  popd

  cd testflight/

  source ./scripts/preflight

  go install github.com/onsi/ginkgo/ginkgo

  ginkgo -r -v
