---
networks:
  - name: concourse
    subnets:
      # network with static ip used for web
      - range: 10.244.15.0/30
        gateway: 10.244.15.1
        static: [10.244.15.2]
      # networks for dynamic ips (compilation vms)
      - range: 10.244.15.4/30
        gateway: 10.244.15.5
      - range: 10.244.15.8/30
        gateway: 10.244.15.9
      - range: 10.244.15.12/30
        gateway: 10.244.15.13
      - range: 10.244.15.16/30
        gateway: 10.244.15.17
      - range: 10.244.15.20/30
        gateway: 10.244.15.21

vm_types:
  - name: concourse
    network: concourse

compilation:
  workers: 3
  network: concourse
