---
name: concourse-testflight

director_uuid: ~

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

instance_groups:
  - name: concourse
    instances: 1
    networks:
      - name: concourse
        static_ips: [&web-ip 10.244.15.2]
    persistent_disk: 10240
    resource_pool: concourse
    jobs:
      - release: concourse
        name: atc
        properties:
          # turn off and provide auth for a real vagrant instance
          development_mode: true

          default_check_interval: 5s

          external_url: http://10.244.15.2:8080

          postgresql_database: atc
          postgresql:
            address: 127.0.0.1:5432
            role:
              name: atc
              password: dummy-password

      - release: concourse
        name: tsa
        properties:
          atc:
            address: 127.0.0.1:8080

      - release: concourse
        name: groundcrew
        properties:
          tsa:
            host: 127.0.0.1

      - release: concourse
        name: postgresql
        properties:
          databases:
          - name: atc
            role: atc
            password: dummy-password

      - release: concourse
        name: baggageclaim

      - release: garden-linux
        name: garden
        properties:
          garden:
            listen_network: tcp
            listen_address: 0.0.0.0:7777
            allow_host_access: true

networks:
  - name: concourse
    subnets:
      # network with static ip used for web
      - range: 10.244.15.0/30
        reserved: [10.244.15.1]
        static: [10.244.15.2]
        cloud_properties: {}

      # networks for dynamic ips (compilation vms)
      - range: 10.244.15.4/30
        reserved: [10.244.15.5]
        cloud_properties: {}
      - range: 10.244.15.8/30
        reserved: [10.244.15.9]
        cloud_properties: {}
      - range: 10.244.15.12/30
        reserved: [10.244.15.13]
        cloud_properties: {}
      - range: 10.244.15.16/30
        reserved: [10.244.15.17]
        cloud_properties: {}
      - range: 10.244.15.20/30
        reserved: [10.244.15.21]
        cloud_properties: {}

resource_pools:
  - name: concourse
    network: concourse
    cloud_properties: {}
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest

compilation:
  workers: 3
  network: concourse
  cloud_properties: {}

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-300000
  update_watch_time: 1000-300000
