---
name: concourse-testflight

director_uuid: ~

releases:
  - name: concourse
    version: latest
  - name: garden-linux
    version: latest

instance_groups:
  - name: concourse
    instances: 1
    networks:
      - name: concourse
        static_ips: [&web-ip 10.244.15.2]
    persistent_disk: 10240
    vm_type: concourse
    stemcell: trusty
    jobs:
      - release: concourse
        name: atc
        properties:
          # turn off and provide auth for a real vagrant instance
          development_mode: true
          default_check_interval: 5s
          external_url: http://10.244.15.2:8080
          postgresql_database: atc

      - release: concourse
        name: tsa
        properties: {}

      - release: concourse
        name: postgresql
        properties:
          databases:
          - name: atc
            role: atc
            password: dummy-password

  - name: default_worker
    instances: 1
    networks: [name: concourse]
    vm_type: concourse
    stemcell: trusty
    jobs:
      - release: concourse
        name: groundcrew
        consumes:
          baggageclaim: {from: default_worker_baggageclaim}
        properties: {}

      - release: concourse
        name: baggageclaim
        provides:
          baggageclaim: {as: default_worker_baggageclaim}
        properties: {}

      - release: garden-linux
        name: garden
        properties:
          garden:
            listen_network: tcp
            listen_address: 0.0.0.0:7777
            allow_host_access: true

  - name: proxy_worker
    instances: 1
    networks: [name: concourse]
    vm_type: concourse
    stemcell: trusty
    jobs:
      - release: concourse
        name: groundcrew
        consumes:
          baggageclaim: {from: proxy_worker_baggageclaim}
        properties:
          tags: ["proxy"]
          http_proxy_url: proxy.example.com

      - release: concourse
        name: baggageclaim
        provides:
          baggageclaim: {as: proxy_worker_baggageclaim}
        properties: {}

      - release: garden-linux
        name: garden
        properties:
          garden:
            listen_network: tcp
            listen_address: 0.0.0.0:7777
            allow_host_access: true

stemcells:
  - alias: trusty
    os: ubuntu-trusty
    version: latest

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-300000
  update_watch_time: 1000-300000
