---
resources:
  - name: some-git-resource
    type: git
    source:
      uri: {{origin-git-server}}
      branch: master

  - name: some-git-resource-success
    type: git
    source:
      uri: {{success-git-server}}
      branch: success

  - name: some-git-resource-failure
    type: git
    source:
      uri: {{failure-git-server}}
      branch: failure

  - name: some-git-resource-no-update
    type: git
    source:
      uri: {{no-update-git-server}}
      branch: no-update

  - name: some-git-resource-ensure-success
    type: git
    source:
      uri: {{ensure-success-git-server}}
      branch: ensure-success

  - name: some-git-resource-ensure-failure
    type: git
    source:
      uri: {{ensure-failure-git-server}}
      branch: ensure-failure

jobs:
  - name: some-passing-job
    plan:
      - get: some-git-resource
        trigger: true
      - task: curl-server
        config:
          platform: linux
          image: {{testflight-helper-image}}
          inputs:
            - name: some-git-resource
              path: .
          params:
            CURL_COMMAND: {{guid-server-curl-command}}
          run:
            path: bash
            args: ["-c", "tail -1 guids | $CURL_COMMAND"]
        ensure:
          put: some-git-resource-ensure-success
          params:
            repository: curl-server
        on_success:
          put: some-git-resource-success
          params:
            repository: curl-server
        on_failure:
          put: some-git-resource-no-update
          params:
            repository: curl-server

  - name: some-failing-job
    plan:
      - get: some-git-resource
        trigger: true
      - task: curl-server
        config:
          platform: linux
          image: {{testflight-helper-image}}
          inputs:
            - name: some-git-resource
              path: .
          run:
            path: bash
            args: ["-c", "exit 1"]
        ensure:
          put: some-git-resource-ensure-failure
          params:
            repository: curl-server
        on_success:
          put: some-git-resource-no-update
          params:
            repository: curl-server
        on_failure:
          put: some-git-resource-failure
          params:
            repository: curl-server

  - name: fancy-build-matrix
    plan:
      - get: some-git-resource
        trigger: true
      - aggregate:
          - task: passing-unit-1
            config:
              platform: linux
              image: {{testflight-helper-image}}
              run:
                path: touch
                args: [file]
          - task: passing-unit-2
            config:
              platform: linux
              image: {{testflight-helper-image}}
              run:
                path: touch
                args: [file]
      - task: curl-server
        config:
          platform: linux
          image: {{testflight-helper-image}}
          inputs:
            - name: passing-unit-1
            - name: passing-unit-2
            - name: some-git-resource
          params:
            CURL_COMMAND: {{guid-server-curl-command}}
          run:
            path: bash
            args: ["-c", '{ echo $(ls passing-unit-*/file) $(tail -1 some-git-resource/guids); } | $CURL_COMMAND']
      - aggregate:
          - task: second-passing-unit-1
            config:
              platform: linux
              image: {{testflight-helper-image}}
              run:
                path: sh
                args: [-c, exit 0]
          - task: second-failing-unit-2
            config:
              platform: linux
              image: {{testflight-helper-image}}
              run:
                path: sh
                args: [-c, exit 1]
      - task: curl-server-failure
        conditions: [failure]
        config:
          platform: linux
          image: {{testflight-helper-image}}
          inputs:
            - name: some-git-resource
          params:
            CURL_COMMAND: {{guid-server-curl-command}}
          run:
            path: bash
            args: ["-c", '{ echo failed $(tail -1 some-git-resource/guids); } | $CURL_COMMAND']

  - name: try-job
    plan:
      - get: some-git-resource
        trigger: true
      - try:
          task: failing-task
          config:
            platform: linux
            image: {{testflight-helper-image}}
            run:
              path: bash
              args: ["-c", "exit 1"]
      - task: passing-task
        config:
          platform: linux
          image: {{testflight-helper-image}}
          inputs:
            - name: some-git-resource
              path: .
          run:
            path: bash
            args: ["-c", "echo passing-task succeeded"]

  - name: failing-job
    plan:
      - get: some-git-resource
        trigger: true
      - task: failing-task
        config:
          platform: linux
          image: {{testflight-helper-image}}
          run:
            path: bash
            args: ["-c", "exit 1"]

  - name: duration-successful-job
    plan:
      - get: some-git-resource
        trigger: true
      - task: passing-task
        timeout: 10m
        config:
          platform: linux
          image: {{testflight-helper-image}}
          run:
            path: bash
            args: ["-c", "echo passing-task succeeded"]

  - name: duration-fail-job
    plan:
      - get: some-git-resource
        trigger: true
      - task: timeout-task
        timeout: 5s
        config:
          platform: linux
          image: {{testflight-helper-image}}
          run:
            path: bash
            args: ["-c", "sleep 10"]

