---
resources:
  - name: some-git-resource
    type: git
    source:
      uri: {{origin-git-server}}
      branch: master

  - name: some-git-resource-success
    type: git
    source:
      uri: {{success-git-server}}
      branch: success

  - name: some-git-resource-failure
    type: git
    source:
      uri: {{failure-git-server}}
      branch: failure

  - name: some-git-resource-no-update
    type: git
    source:
      uri: {{no-update-git-server}}
      branch: no-update

jobs:
  - name: some-passing-job
    plan:
      - get: some-git-resource
        trigger: true
      - task: curl-server
        config:
          platform: linux
          image: {{testflight-helper-image}}
          inputs:
            - name: some-git-resource
              path: .
          params:
            CURL_COMMAND: {{guid-server-curl-command}}
          run:
            path: bash
            args: ["-c", "tail -1 guids | $CURL_COMMAND"]
      - put: some-git-resource-success
        params:
          repository: curl-server

  - name: some-failing-job
    plan:
      - get: some-git-resource
        trigger: true
      - task: curl-server
        config:
          platform: linux
          image: {{testflight-helper-image}}
          inputs:
            - name: some-git-resource
              path: .
          run:
            path: bash
            args: ["-c", "exit 1"]
      - aggregate:
          - put: some-git-resource-no-update
            params:
              repository: curl-server
          - put: some-git-resource-failure
            conditions: [failure]
            params:
              repository: curl-server

  - name: fancy-build-matrix
    plan:
      - get: some-git-resource
        trigger: true
      - aggregate:
          - task: passing-unit-1
            config:
              platform: linux
              image: {{testflight-helper-image}}
              run:
                path: touch
                args: [file]
          - task: passing-unit-2
            config:
              platform: linux
              image: {{testflight-helper-image}}
              run:
                path: touch
                args: [file]
      - task: curl-server
        config:
          platform: linux
          image: {{testflight-helper-image}}
          inputs:
            - name: passing-unit-1
            - name: passing-unit-2
            - name: some-git-resource
          params:
            CURL_COMMAND: {{guid-server-curl-command}}
          run:
            path: bash
            args: ["-c", '{ echo $(ls passing-unit-*/file) $(tail -1 some-git-resource/guids); } | $CURL_COMMAND']
      - aggregate:
          - task: second-passing-unit-1
            config:
              platform: linux
              image: {{testflight-helper-image}}
              run:
                path: sh
                args: [-c, exit 0]
          - task: second-failing-unit-2
            config:
              platform: linux
              image: {{testflight-helper-image}}
              run:
                path: sh
                args: [-c, exit 1]
      - task: curl-server-failure
        conditions: [failure]
        config:
          platform: linux
          image: {{testflight-helper-image}}
          inputs:
            - name: some-git-resource
          params:
            CURL_COMMAND: {{guid-server-curl-command}}
          run:
            path: bash
            args: ["-c", '{ echo failed $(tail -1 some-git-resource/guids); } | $CURL_COMMAND']
