---
resources:
- name: some-git-resource
  type: git
  source:
    uri: {{.GitServer.Origin}}
    branch: master

- name: some-git-resource-success
  type: git
  source:
    uri: {{.GitServer.Success}}
    branch: success

- name: some-git-resource-failure
  type: git
  source:
    uri: {{.GitServer.Failure}}
    branch: failure

- name: some-git-resource-no-update
  type: git
  source:
    uri: {{.GitServer.NoUpdate}}
    branch: no-update

jobs:
- name: some-job
  config:
    image: {{.TestflightHelperImage}}
    run:
      path: bash
      args: ["-c", "tail -1 some-git-resource/guids | {{.GuidServerCurlCommand}}"]
  inputs:
  - resource: some-git-resource
  outputs:
  - resource: some-git-resource-success
    params:
      repository: some-git-resource

- name: some-failing-job
  config:
    image: {{.TestflightHelperImage}}
    run:
      path: bash
      args: ["-c", "exit 1"]
  inputs:
  - resource: some-git-resource
  outputs:
  - resource: some-git-resource-no-update
    params:
      repository: some-git-resource
  - resource: some-git-resource-failure
    on: [failure]
    params:
      repository: some-git-resource
