---
image: concourse/testflight

env:
  - GOROOT=/usr/local/go
  - PATH=$GOROOT/bin:$PATH
  - GOPATH=/tmp/build/src/testflight
  - PATH=$GOPATH/bin:$PATH
  - DOCKER_REGISTRY_CONFIG=/docker-registry/config/config_sample.yml
  - EXTERNAL_ADDRESS=$(ip route get 8.8.8.8 | sed 's/.*src\s\(.*\)\s/\1/;tx;d;:x')

script: |
  set -e -x

  pushd $GOPATH/src/github.com/cloudfoundry-incubator/warden-linux
    make # compile wshd/etc.
    export WARDEN_BINPATH=$PWD/linux_backend/bin
  popd

  cd $GOPATH/src/github.com/concourse/testflight/

  source ./scripts/preflight

  go install github.com/onsi/ginkgo/ginkgo

  ginkgo -r -v
