---
name: ((deployment_name))

releases:
  - name: concourse
    version: ((concourse_version))
  - name: garden-runc
    version: ((garden_runc_version))

instance_groups:
- name: concourse
  instances: 1
  networks:
    - name: testflight
      static_ips: [&web-ip ((web_ip))]
  persistent_disk: 10240
  vm_type: testflight
  stemcell: trusty
  jobs:
    - release: concourse
      name: atc
      properties:
        tls_bind_port: 4443
        log_level: debug
        default_check_interval: 5s
        external_url: https://((web_ip)):4443
        postgresql_database: atc

        tls_cert: ((tls_cert))
        tls_key: ((tls_key))
        no_really_i_dont_want_any_auth: true

    - release: concourse
      name: tsa
      properties: {}

    - release: concourse
      name: postgresql
      properties:
        databases:
        - name: atc
          role: atc
          password: dummy-password

    - release: concourse
      name: groundcrew
      properties: {}

    - release: concourse
      name: baggageclaim
      properties: {}

    - release: garden-runc
      name: garden
      properties:
        garden:
          listen_network: tcp
          listen_address: 0.0.0.0:7777
          allow_host_access: true

stemcells:
  - alias: trusty
    os: ubuntu-trusty
    version: latest

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-300000
  update_watch_time: 1000-300000
